### ISSUE TITLE
update

### ISSUE THREAD

**Issue by bigmac5753** [Pamenarti/lotus-blockchain#12]
is there an update on this project?  has it been abandoned?

**Comment by Pamenarti** [comment]
not abandoned. We are developing a different consensus. We will add multi mining system.  this will take some time.

**Comment by bigmac5753** [comment]
Sounds interesting, if you need testers, let me know.

**Comment by ralf9090** [comment]
Testera benide yazabilirsin ✌️

**Comment by mgrubiak** [comment]
make a discord server, do some hype around the project

**Comment by Pamenarti** [comment]
It has been shelved for now due to lack of support.
