### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 1617176084** [Pamenarti/lotus-blockchain#2]
I can't run him properly

![30461624590161_ pic_hd](https://user-images.githubusercontent.com/7008899/123363607-74c01e80-d5a5-11eb-95f1-687e68a77176.jpg)

**Comment by Pamenarti** [comment]
The arrangements are not over yet.

**Comment by 1617176084** [comment]
> The arrangements are not over yet.

So when can it be used properly?Do you have an email address?I think it's easier to get in touch

**Comment by Pamenarti** [comment]
will be up and running soon.
email : pamenarti@gmail.com.
